### PR TITLE
Delete README.md Pull Req

### PR DESCRIPTION
**Pull request by jhonRo-Testing-Acc**
no write access so creating fork

### CODE REVIEW

**Comment by rozon108** [comment]
deleted file is required for this project

**Review by rozon108 — APPROVED** [review]

**Comment by jhonRo-Testing-Acc** [comment]
role changed to mainter, can't merge but I can comment, approve and close pull request

**Review by rozon108 — CHANGES_REQUESTED** [review]
changes

**Comment by jhonRo-Testing-Acc** [comment]
actually, Role: Maintainer
Can Merge pull request, comment . can't approve or request change

**Comment by jhonRo-Testing-Acc** [comment]
Changed ROLE: READ
Comment and close

No accès to merge.

**Review by jhonRo-Testing-Acc — COMMENTED** [review]
done changes

**Review by rozon108 — APPROVED** [review]

**Pull request closed without merging**
